[package]
name = "bevy_games_workspace"
version = "0.1.0"
edition = "2024"

[dependencies]

[workspace]
members = ["flappy_dragon", "pig", "hello_bevy", "my_library", "bouncy", "mars_base_one", "highscore_server"]

[workspace.dependencies]
bevy = "0.16"
bevy_egui = "0.34.1"
anyhow = "1.0.100"
